name: Build product

on: [push]
jobs:
  one:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: ${{ steps.detect-package-manager.outputs.manager }}
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm build
        env:
          CI: true
