name: Build product

on: [push]
jobs:
  one:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Init node env
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm build
        env:
          CI: true
